import type { SourceSpan } from "./source";

export const TokenKind = {
  Identifier: "Identifier",
  Integer: "Integer",
  ByteLiteral: "ByteLiteral",
  StringLiteral: "StringLiteral",
  RegexLiteral: "RegexLiteral",
  TokenInputLiteral: "TokenInputLiteral",
  LineInputLiteral: "LineInputLiteral",
  Val: "Val",
  Var: "Var",
  Fn: "Fn",
  Return: "Return",
  Break: "Break",
  Continue: "Continue",
  For: "For",
  Times: "Times",
  While: "While",
  Input: "Input",
  Line: "Line",
  Require: "Require",
  If: "If",
  Else: "Else",
  True: "True",
  False: "False",
  Int: "Int",
  String: "String",
  Array: "Array",
  ArrayV: "ArrayV",
  Byte: "Byte",
  Regex: "Regex",
  Bool: "Bool",
  Unit: "Unit",
  Colon: "Colon",
  Comma: "Comma",
  Semicolon: "Semicolon",
  LeftBracket: "LeftBracket",
  RightBracket: "RightBracket",
  LeftBrace: "LeftBrace",
  RightBrace: "RightBrace",
  Plus: "Plus",
  PlusEqual: "PlusEqual",
  Minus: "Minus",
  MinusEqual: "MinusEqual",
  Star: "Star",
  StarEqual: "StarEqual",
  Slash: "Slash",
  SlashEqual: "SlashEqual",
  Percent: "Percent",
  PercentEqual: "PercentEqual",
  LeftParen: "LeftParen",
  RightParen: "RightParen",
  Bang: "Bang",
  BangEqual: "BangEqual",
  EqualEqual: "EqualEqual",
  Assign: "Assign",
  Less: "Less",
  LessEqual: "LessEqual",
  Greater: "Greater",
  GreaterEqual: "GreaterEqual",
  AndAnd: "AndAnd",
  OrOr: "OrOr",
  DotDot: "DotDot",
  DotDotEqual: "DotDotEqual",
  Dot: "Dot",
  EndOfFile: "EndOfFile",
} as const;

export type TokenKind = (typeof TokenKind)[keyof typeof TokenKind];

export interface Token {
  readonly kind: TokenKind;
  readonly lexeme: string;
  readonly span: SourceSpan;
}
